"""Project-wide constants for Exile of the Doomed."""

from __future__ import annotations

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
WINDOW_TITLE = "Исход Обречённых"
FULLSCREEN = True

FPS_LIMIT = 120
FIXED_TIME_STEP = 1.0 / 60.0
MAX_FRAME_TIME = 0.25

WORLD_WIDTH = 2400
WORLD_HEIGHT = 1600
SYSTEM_COUNT_MIN = 7
SYSTEM_COUNT_MAX = 10
GALAXY_WIDTH = 100
GALAXY_HEIGHT = 60
BSP_MIN_LEAF_SIZE = 14
BSP_MAX_DEPTH = 5

PLAYER_RADIUS = 22
PLAYER_MAX_HEALTH = 140.0
PLAYER_MAX_SHIELDS = 90.0
PLAYER_MAX_ENERGY = 100.0
PLAYER_ACCELERATION = 680.0
PLAYER_MAX_SPEED = 360.0
PLAYER_FRICTION = 0.86
PLAYER_FIRE_COOLDOWN = 0.16
PLAYER_WEAPONS = (
    {
        "name": "Импульс",
        "cooldown": 0.16,
        "energy_cost": 4.0,
        "damage": 18.0,
        "speed": 720.0,
        "lifetime": 1.8,
    },
    {
        "name": "Пробойник",
        "cooldown": 0.44,
        "energy_cost": 13.0,
        "damage": 42.0,
        "speed": 560.0,
        "lifetime": 2.25,
    },
)

ANCIENT_RADIUS = 24
ANCIENT_MAX_HEALTH = 85.0
ANCIENT_ACCELERATION = 430.0
ANCIENT_MAX_SPEED = 240.0
ANCIENT_FIRE_COOLDOWN = 0.75
ANCIENT_DETECTION_RADIUS = 620.0
ANCIENT_FLEE_HEALTH_RATIO = 0.28

PROJECTILE_RADIUS = 4
PROJECTILE_SPEED = 720.0
PROJECTILE_LIFETIME = 1.8
PLAYER_PROJECTILE_DAMAGE = 18.0
ANCIENT_PROJECTILE_DAMAGE = 12.0

ASTEROID_MIN_RADIUS = 18
ASTEROID_MAX_RADIUS = 52
ASTEROID_COUNT_MIN = 22
ASTEROID_COUNT_MAX = 42
ANCIENT_COUNT_MIN = 4
ANCIENT_COUNT_MAX = 8

PLANET_RADIUS = 72
PLANET_CHANCE = 0.5
PLANET_INTERACTION_DISTANCE = 170.0
PLANET_QUEST_REWARD = 45

QUADTREE_CAPACITY = 6
QUADTREE_MAX_DEPTH = 7

SAVE_FILE = "save.dat"
LOG_LEVEL_ENV = "LOG_LEVEL"

BACKGROUND_CELL_SIZE = 6
BACKGROUND_NOISE_SCALE = 0.013

HIT_EFFECT_DURATION = 0.28

MUSIC_VOLUME = 0.45
MUSIC_FADE_MS = 1800
LOBBY_TRACK = "alexander-nakarada-chase.mp3"

UPGRADE_COSTS = {
    "hull": 60,
    "shields": 55,
    "engine": 70,
    "reactor": 65,
    "weapons": 80,
}
UPGRADE_LABELS = {
    "hull": "Корпус",
    "shields": "Щиты",
    "engine": "Двигатель",
    "reactor": "Реактор",
    "weapons": "Урон пушек",
}
